### PR TITLE
API makes more sense this way

### PR DESCRIPTION
**Pull request by stereobooster**
And I have this code:

```js
import React from "react";

import { getUseStyle } from "./useStyle";

export const singletoneStyled = styles => {
  const useStyle = getUseStyle(styles);

  const get = (_, defaultAs, __) => defaultClass => {
    const component = React.memo(
      React.forwardRef(({ children, as = defaultAs, ...props }, ref) => {
        useStyle();
        return React.createElement(
          as,
          { ...props, className: defaultClass, ref },
          children
        );
      })
    );
    component.displayName = `${defaultClass}💅`;
    return component;
  };

  // browser support https://caniuse.com/#search=proxy
  return new Proxy({}, { get });
};
```

can be use like this

```js
const css = strings => strings[0];
const styled = singletoneStyled(css`
  .Center {
    display: flex;
    justify-content: center;
    align-items: center;
  }
`);
const Center = styled.div("Center");
```

### CODE REVIEW

**Comment by theKashey** [comment]
Not always. Let's add it as an optional argument for the `singleton` call, so you will be able to override it in the "old way".

Why I want the old way to be kept? __Lazy evaluation__ and `props` access - you just don't have access to props outside of the component(you might not need it), and style generation during page spinup - one millisecond here(a bit more for me), another there - you know how it could be :) a thousand cuts to death.

**Comment by theKashey** [comment]
To make it work properly #1 should be implemented - to have one style tag, with all the rules inside. It's more about - there are some problems with index-based `deleteRule` and I didn't played with it yet. Some articles proposed "keep" the index, and work with it on even lower level - https://stackoverflow.com/questions/46941964/update-or-remove-css-rule-from-insertrule-in-js

**Comment by stereobooster** [comment]
Do we understanding code the same way?

```js
import {styleHookSingleton} from 'react-style-singleton';

const useStyle = styleHookSingleton();

export const A = () => {
  useStyle('div {color:red}' );
  return (<div />);
}

export const B = () => {
  useStyle('div {color:blue}' );
  return (<div />);
}
```

it will be either red or blue, never both, right? That is why I'm saying the change makes more sense, because with change there is no way to confuse things

>  Lazy evaluation 

But nothing is changed about laziness - stylesheet is inserted upon first use not before

**Comment by stereobooster** [comment]
This is just a proposal. I code for fun here

**Comment by theKashey** [comment]
> But nothing is changed about laziness - stylesheet is inserted upon first use not before

```css
body {
  margin-right: ${getScrollBarWidth()}px;
}
```

**Comment by stereobooster** [comment]
You need to give me a bit more context. To be sure we are on the same page `useEffect` (which was introduced in previous PR, not in this one) runs after first render (the same way as `componentDidMount`). Right? As well because we provide empty array it will run only once for component.

```js
import {styleHookSingleton} from 'react-style-singleton';
const useStyle = styleHookSingleton('div {color:red}');
// nothing inserted in DOM yet
export const App = () => {
  useStyle();
}
// nothing inserted in DOM yet
ReactDOM.render(<App />, document.getElementById("app"));
// after first render stylesheet is inserted
```

**Comment by stereobooster** [comment]
I got what you saying. Makes sense. Except the value will never update, which was strange for me

**Comment by theKashey** [comment]
There are always different options, your point about having a single source of truth is valid enought.
```
const useStyle = styleHookSingleton(() => 'div {
   color:red;
   margin-right: ${getScrollBarWidth()}px;
}');
// nothing inserted in DOM yet
export const App = () => {
  useStyle();
}

**Pull request closed without merging**
